# Generated by Django 6.0.4 on 2026-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='changed_by',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
